#' Replace ID column
#' 
#' This function replaces an ID column in a dataframe with another ID, given a lookup table
#' @param dataset The input data.frame that contains the id to be replaced
#' @param col_toreplace A string that is the name of the column to be replaced
#' @param lookup The lookup 2-column data.frame that contains the original column as the first column and the corresponding IDs as the second. Ideally generated by \code{"create_lookup"}
#' @return A data.frame which is like the original except that the ID column is replaced with its corresponding entry in the lookup table
#' @export

replace_idcol <- function(dataset, col_toreplace, lookup){
  # save the names of the original dataset
  df_names <- names(dataset)
  
  # Set the by parameter for dplyr's left_Join 
  # Cannot do in-line due to eval method
  named_char <- c("original.ID")
  names(named_char) <- col_toreplace
  
  # Join with the lookup table
  replacement_df <- dplyr::left_join(x=dataset, y=lookup, by=named_char)
  
  # Drop the original column
  replacement_df[[col_toreplace]] <- NULL
  # Replace with the new one
  df_names[which(df_names == col_toreplace)] <- "replacement.ID"
  # Reorder the dataframe
  replacement_df <- replacement_df[,df_names]
  replacement_df
}